# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: 'Seascape Sport Horses - Santa Cruz, CA - Hunter/Jumper Training & Lessons'
email: seascapesporthorses@gmail.com
author: Charis Dankert & Shannon Wilson
description: >
  Seascape Sport Horses specializes in importing high-end hunter, jumper, and equitation horses for the Santa Cruz area. Offering elite horseback riding lessons for all levels. Located in Bonny Doon CA.
copyright: 'Copyright &copy; 2016 Seascape Sport Horses. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/Seascape-Sport-Horses-1174945482517873/
  - title: instagram
    url: https://www.instagram.com/seascapesporthorses/
  - title: youtube
    url: https://www.youtube.com/channel/UC4p-58EHq0rpY6Qjzg5GPUw
