# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Seascape Sport Horses - Gilroy, CA - Hunter/Jumper Training & Lessons
email: seascapesporthorses@gmail.com
author: Charis Dankert & Shannon Wilson
description: >
  Seascape Sport Horses specializes in importing high-end hunter, jumper, and equitation horses for Gilroy, Morgan Hill, San Jose, and the Bay Area area. Offering elite horseback riding lessons for all levels. Located in Gilroy CA.
copyright: Copyright &copy; 2018 Seascape Sport Horses

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
